trigger:
- main

resources:
- repo: self

variables:  
  IMAGE_NAME: philoezzat/csharp-backend
  CONTAINERAPPS_APP: back-end-api
  CONTAINERAPPS_ENVIRONMENT: managedEnvironment-task1-947b
  RESOURCE_GROUP: task1
  TAG: '$(Build.BuildId)'  # Use Build ID as tag, without prefix

stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/backend_api_csharp/Dockerfile'
        repository: $(IMAGE_NAME)
        tags: |
          $(TAG)

  - job: Push
    displayName: Push
    dependsOn: Build  # Ensure Push runs after Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Push image to Docker Hub
      inputs:
        containerRegistry: 'docker-hub connection'  # Ensure this is set up correctly
        repository: $(IMAGE_NAME)
        command: 'push'
        tags: |
          $(TAG)  # Use only the tag, assuming IMAGE_NAME includes the repo

- stage: Deploy
  displayName: Deploy to Container Apps
  dependsOn: Build  # Ensure Deploy runs after Push
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureContainerApps@1
      displayName: Deploy new container version
      inputs:
        azureSubscription: 'azure-connection'
        imageToDeploy: '$(IMAGE_NAME):$(TAG)'
        containerAppName: '$(CONTAINERAPPS_APP)'
        resourceGroup: '$(RESOURCE_GROUP)'
        containerAppEnvironment: '$(CONTAINERAPPS_ENVIRONMENT)'
        targetPort: '3500'
        ingress: 'external'
