trigger:
- main

resources:
- repo: self

variables:  
  IMAGE_NAME: philoezzat/csharp-backend  # Ensure this is your Docker Hub username/repo
  CONTAINERAPPS_APP: back-end-api
  CONTAINERAPPS_ENVIRONMENT: managedEnvironment-task1-947b
  RESOURCE_GROUP: task1
  TAG: '$(Build.BuildId)'  # Use Build ID as tag, without prefix

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Building Docker image..."
        echo "Image Name: $(IMAGE_NAME)"
        echo "Tag: $(TAG)"
      displayName: 'Log Image Name and Tag'

    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/backend_api_csharp/Dockerfile'
        repository: $(IMAGE_NAME)
        tags: |
          $(TAG)

    - script: docker images
      displayName: 'List Docker Images'  # Ensure image was built successfully

  - job: Push
    displayName: Push Image to Docker Hub
    dependsOn: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Preparing to push Docker image..."
        echo "Image Name: $(IMAGE_NAME)"
        echo "Tag: $(TAG)"
        echo "Push command: docker push $(IMAGE_NAME):$(TAG)"
      displayName: 'Log Image Name, Tag, and Push Command'

    - task: Docker@2
      displayName: Push Docker Image to Docker Hub
      inputs:
        containerRegistry: 'docker-hub connection'  # Ensure the Docker Hub connection is correct
        repository: $(IMAGE_NAME)
        command: 'push'
        tags: |
          $(TAG)

- stage: Deploy
  displayName: Deploy to Container Apps
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureContainerApps@1
      displayName: Deploy New Container Version
      inputs:
        azureSubscription: 'azure-connection'
        imageToDeploy: '$(IMAGE_NAME):$(TAG)'  # Use the full image name with tag
        containerAppName: '$(CONTAINERAPPS_APP)'
        resourceGroup: '$(RESOURCE_GROUP)'
        containerAppEnvironment: '$(CONTAINERAPPS_ENVIRONMENT)'
        targetPort: '3500'
        ingress: 'external'
