trigger:
- main

resources:
- repo: self

variables:  
  IMAGE_NAME: philoezzat/csharp-backend
  CONTAINERAPPS_APP: back-end-api
  CONTAINERAPPS_ENVIRONMENT: managedEnvironment-task1-947b
  RESOURCE_GROUP: task1
  TAG: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/backend_api_csharp/Dockerfile'
        repository: $(IMAGE_NAME)
        tags: |
          $(TAG)

  